# See https://docs.rubocop.org/rubocop/configuration

AllCops:
  Exclude:
    - "data/**/*"
    - "db/schema.rb"
    - "node_modules/**/*"
    - "vendor/**/*"
  NewCops: enable

Layout/LineLength:
  Max: 120

Layout/SpaceAroundBlockParameters:
  EnforcedStyleInsidePipes: "space"

Layout/SpaceInsideArrayLiteralBrackets:
  EnforcedStyle: "space"

Layout/SpaceInsideParens:
  EnforcedStyle: "space"

Layout/SpaceInsideReferenceBrackets:
  EnforcedStyle: "space"

Layout/SpaceInsideStringInterpolation:
  EnforcedStyle: "space"

Metrics/MethodLength:
  Max: 25

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: "double_quotes"

Style/SymbolArray:
  EnforcedStyle: "brackets"

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: "consistent_comma"
