version: "3.9"
services:
  db:
    image: postgres:13.4
    environment:
      - POSTGRES_DB=${MAITRE_D_DB_DATABASE}
      - POSTGRES_PASSWORD=${MAITRE_D_DB_PASSWORD}
      - POSTGRES_USER=${MAITRE_D_DB_USERNAME}
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./data/pg:/var/lib/postgresql/data
  web-app:
    build: .
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://${MAITRE_D_DB_USERNAME}:${MAITRE_D_DB_PASSWORD}@db:5432
      - RACK_ENV=development
      - RAILS_ENV=development
    ports:
      - 3000:3000